var i = 1;
global.Item_Sprite[argument[0]] = argument[i++];
global.Item_Text[argument[0]] = argument[i++];
global.Item_MaxCount[argument[0]] = argument[i++];
global.Item_Desc[argument[0]] = argument[i++];
global.Item_OnUse[argument[0]] = argument[i++];
global.Item_OnEquip[argument[0]] = argument[i++];
global.Item_OnQuickSlot[argument[0]] = argument[i++];
global.Item_UserParam[argument[0]] = argument[i++];
